SELECT * FROM tabela_de_produtos;

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
CASE 
	WHEN PRECO_DE_LISTA >= 12 THEN 'CARO' 
	WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'EM CONTA' 
	ELSE 'BARATO' 
END AS STATUS_PRECO 
FROM TABELA_DE_PRODUTOS;

SELECT NOME,
CASE 
	WHEN YEAR(DATA_DE_NASCIMENTO) < 1990 THEN 'VELHOS' 
	WHEN YEAR(DATA_DE_NASCIMENTO) >= 1990 AND YEAR(DATA_DE_NASCIMENTO) < 1995 THEN 'JOVENS' 
	ELSE 'CRIANÇAS' 
END AS CLASSIFICACAO FROM TABELA_DE_CLIENTES;


