SELECT * FROM tabela_de_produtos ORDER BY PRECO_DE_LISTA ASC LIMIT 5;

SELECT * FROM tabela_de_produtos WHERE NOME_DO_PRODUTO='Linha Refrescante - 1 Litro - Morango/Limão'; 


SELECT * FROM ITENS_notas_fiscais WHERE CODIGO_DO_PRODUTO='1101035' ORDER BY QUANTIDADE DESC LIMIT 1;
