USE suco_vendas;

SELECT CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, 
DATA_DE_NASCIMENTO, IDADE, SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA,
PRIMEIRA_COMPRA FROM tabela_de_clientes;

SELECT * FROM tabela_de_clientes;

SELECT CPF, NOME FROM tabela_de_clientes;

SELECT CPF AS IDENTIFICADOR, NOME AS CLIENTE FROM tabela_de_clientes;

SELECT * FROM TABELA_DE_PRODUTOS WHERE CODIGO_DO_PRODUTO= '1000889';

SELECT * FROM tabela_de_produtos WHERE SABOR = 'Laranja';

