SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos;

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos WHERE SABOR = 'LARANJA';

SELECT DISTINCT EMBALAGEM, TAMANHO FROM tabela_de_produtos WHERE SABOR = 'LARANJA';

SELECT DISTINCT BAIRRO FROM tabela_de_clientes WHERE CIDADE='RIO DE JANEIRO';