SELECT DISTINCT BAIRRO FROM tabela_de_vendedores;

SELECT * FROM tabela_de_clientes WHERE BAIRRO IN (SELECT DISTINCT BAIRRO FROM tabela_de_vendedores);


SELECT X.EMBALAGEM, X.PRECO_MAX FROM
(SELECT EMBALAGEM, MAX(PRECO_DE_LISTA) AS PRECO_MAX FROM tabela_de_produtos GROUP BY EMBALAGEM) X
WHERE X.PRECO_MAX >= 10 ;


## ------ exercício ---------- ##

SELECT * FROM itens_notas_fiscais;
SELECT * FROM NOTAS_FISCAIS;
SELECT * FROM TABELA_DE_CLIENTES;

SELECT CPF, COUNT(*) FROM notas_fiscais
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY CPF
HAVING COUNT(*) > 2000;

SELECT X.CPF, X.CONTADOR FROM 
(SELECT CPF, COUNT(*) AS CONTADOR FROM notas_fiscais
WHERE YEAR(DATA_VENDA) = 2016
GROUP BY CPF) X WHERE X.CONTADOR > 2000